CREATE TABLE `salary` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `emp_id` int(10) unsigned NOT NULL,
  `basic` decimal(7,2) unsigned NOT NULL,
  `hra` decimal(7,2) unsigned NOT NULL,
  `gratuity` decimal(7,2) unsigned NOT NULL,
  `bonus` decimal(7,2) unsigned NOT NULL,
  `retention_bonus` decimal(7,2) unsigned NOT NULL,
  `dearness_allowance` decimal(7,2) unsigned NOT NULL,
  `transport_allowance` decimal(7,2) unsigned NOT NULL,
  `leave_travel_allowance` decimal(7,2) unsigned NOT NULL,
  `special_allowance` decimal(7,2) unsigned NOT NULL,
  `other_allowance` decimal(7,2) unsigned NOT NULL,
  `food_coupons` decimal(7,2) unsigned NOT NULL,
  `medical_reimbursement` decimal(7,2) unsigned NOT NULL,
  `car_expense_reimbursement` decimal(7,2) unsigned NOT NULL,
  `tel_expense_reimbursement` decimal(7,2) unsigned NOT NULL,
  `pf` decimal(7,2) NOT NULL,
  `tds` decimal(7,2) NOT NULL,
  `professional_tax` decimal(7,2) NOT NULL,
  `date_of_adding` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `emp_id` (`emp_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
